In [12]:
import numpy as np
list=[10,20,30]
a=np.array(list)
print(a)
print(np.ndim(a))

[10 20 30]
1


In [25]:
import numpy as np
list=[12,24,36],[11,55,63]
a=np.array(list)
print(a)
print(np.ndim(a))


[[12 24 36]
 [11 55 63]]
2


In [39]:
import numpy as np
list=[[[5,6,7],[8,45,67],[12,23,2],[4,5,6]]]
a=np.array(list)
print(a)
print(np.ndim(a))
print(type(a))

[[[ 5  6  7]
  [ 8 45 67]
  [12 23  2]
  [ 4  5  6]]]
3
<class 'numpy.ndarray'>


In [44]:
import numpy as np 
a=np.array([1,2,3])
print(a[-1])

3


In [50]:
import numpy as np 
arr=np.array([[1,2,3,4,5],[5,6,7,8,9]])
print('2nd element of 1st row is', arr[0,0])


2nd element of 1st row is 1


In [58]:
## import numpy as np 
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr[0,2,1])

8


In [75]:
import numpy as np
arr=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]])
print(arr.ndim)
res = arr[0,0,2]+ arr[0,1,2] + arr[0,2,2] + arr[0,3,2]
print(res)

3
30
